name: 'package on push'

on:
  push:
    branches:
      - '*'

jobs:

  package:
    name: build project and generate package
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: set up jdk 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: generate package
        run: |
          export PAT=${{ secrets.PAT }}
          gradle publish