name: 'package on push'

on:
  push:
    branches:
      - '*'

jobs:

  package:
    name: build project and generate package
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: generate package
        run: gradle publish