name: 'package on push'

on:
  push:
    tags:
      - '*.*.*'

jobs:

  package:
    name: build project and generate package
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: set up jdk 11
        uses: actions/setup-java@v3.13.0
        with:
          java-version: 11
          distribution: 'zulu'
          cache: 'gradle'

      - name: generate package
        run: |
          export TOKEN=${{ secrets.TOKEN }}
          ./gradlew -Pversion=${GITHUB_REF#refs/*/} publish
